version: "3.8"
services:
 nginx:
  image: nginx:1.13.7
  container_name: nginx
  depends_on:
   - flask
  volumes:
   - ./nginx.conf:/etc/nginx/conf.d/default.conf
  networks:
   - my-network
  ports:
   - 5000:80
 flask:
  restart: always
  build: ./
  entrypoint:
   - flask
   - run
   - --host=0.0.0.0
  environment:
   - FLASK_APP=app.py
  volumes:
   - "./:/app"
  networks:
   my-network:
    aliases:
     - flask-app
#  ports:
#   - 80:5000
  mem_limit: 256m
  mem_reservation: 128M
  cpus: 0.5
# redis:
#  image: redis
#  container_name: redis-container
#  ports:
#   - "6379:6379"
networks:
    my-network:
