version: '3'
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 5000:80

  flask:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./flask_app
    container_name: flask
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
    volumes:
      - "./flask_app:/web"
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.5


  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

