version: "3.8"
services:
  web:
    restart: always
    build: ./web
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=/web/app.py
      - VIRTUAL_HOST=team4.simulated_HACS.net
      - VIRTUAL_PORT=5001
    volumes:
      - "./web:/web"
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.5
